
spring:
  datasource:
    url: 
    username: 
    password: 
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    initial-size: 1
    max-active: 20
    max-idle: 30
    min-idle: 5
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 'x'
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: false
    max-open-prepared-statements: 20
    filters: stat


  redis:
    host: 
    password: 
    port: 
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1
  activemq:
    broker-url: tcp://10.10.0.6:61616
    user: admin
    password: admin

logging:
  level: debug
  path: /home/five.liu/logs
  file: legowechat
  config: classpath:logback.xml

server:
  port: 9090


wechat:
  mp:
    appId: 
    secret: 
    token: hc90five1218
    aesKey:
    callbackurl: http://wemake.harmontronics.com/wechat/callback


